### ISSUE TITLE
Comparaisons humain/océan

### ISSUE THREAD

**Issue by Wanchai290** [JuliettePetit/ndi-2024#1]
Template à suivre
```
# Titre du problème

## Évènement

## Zones à mettre en surbrillance
Carte du monde : 
Corps humain :

## Nature et conséquences
Carte du monde :
Corps humain :

## (optionnel) Références
```

**Comment by TDecabrat** [comment]
Piste : 
plus d'eau douce
-> eau moins dense

plus d'eau salée
-> eau plus dense

et ça modifie donc l'AMOC

Si eau trop peu dense autour des poles, malgré qu'elle soit froide, elle ne peut plus plonger
puisque pas assez de sel
Donc la circulation va s'arrêter//ralentir grandement
A voir : conséquences directes

**Comment by TDecabrat** [comment]
Deux pistes supplémentaires :
- Comparer barrière de corail avec le système immunitaire
- Comparer phytoplancton + plantes w/ photosynthèse avec les poumons : https://www.portfrejus.fr/poumon-bleu-de-la-planete/

**Comment by Wanchai290** [comment]
# Acidification des océans | Acidose du corps

## Évènement
La compagnie de jeux-vidéos Hoyoverse a fabriqué une nouvelle centrale nucléaire afin de nourrir ses nouveaux data-centers. La pollution mondiale a augmenté de 2%. 

## Zones à mettre en surbrillance
Tout l'océan ?
Estomac du corps et coeur

## Nature et conséquences
Océans: Des études montrent progressivement que l'acidification des océans a un très mauvais impact sur les écosystèmes marins, avec certains animaux marins à squelette qui présentent des anomalies.

Corps: Le corps aussi possède un équilibre acido-basique qui doit rester équilibré. Problème d'acidose, peut créer de grandes fatigues, voire même des problèmes cardiaques.

## (optionnel) Références
https://ocean-climate.org/sensibilisation/les-impacts-du-changement-climatique-sur-locean/
https://www.msdmanuals.com/fr/accueil/troubles-hormonaux-et-m%C3%A9taboliques/%C3%A9quilibre-acidobasique/acidose

**Comment by Neeko-strong-tomato** [comment]
# Sur Absorption de CO2

## Évènement
Production massive de CO2

### Zone en surbrillance
Sur les côtes maritime (pas toutes pour le site mais hassoul)
Poumons

### Nature & Conséquences
Ocean : Les phytoplanctons par la photosynthèse permettent la transformation du CO2 en matière organique et en dioxygène, qui sont tout deux nécessaires à la vie marine. Ce sont les poumons de l'océan. Sans eux la vie n'est possible ni sous l'eau ni sur Terre. La saturtion en CO2 de l'ocean l'empêche d'absorber plus de CO2 qui est rejeté dans l'atmosphère mais empêche aussi l'absorbtion d'autres gazes nécessaires à la vie sous marine.

Humain : 
Dans le corps humain, si les poumons ne sont plus suffisant pour réguler le CO2 et le dioxygène présent dans le corps, la fatigue est amplifié et l'attention baisse jusqu'à l'évanouissement et le malaise causé par le manque de dioxygènes dans les organes vitaux.

**Comment by Wanchai290** [comment]
# Flux sanguins et flux maritimes

## Évènement
(truc marrant qu ies tarrivé). Par conséquent, une partie des calottes glaciaires ont fondu.

## Zones à mettre en surbrillance
Carte du monde : Sortes de traits qui indiquent les flux maritimes (?)
Corps humain : Des traits qui représentent les veines autour du corps

## Nature et conséquences
Carte du monde : circulation océanique impacte la régulation du climat. A cause du réchauffement climatique, les calottes glaciaires augmentent la quantité d'eau douce dans l'océan. Cela ralentit la circulation globale des flux maritimes en empêchant la formation d'eau profonde.

De plus, 

Les conséquences son très mauvaises, car cela diminuerait le carbone et la chaleur absorbés par les océans, et donc accélérer le réchauffement climatique. De plus, Une boucle sans fin.

Corps humain : On peut comparer les flux maritimes avec les flux sanguins du corps. Si le débit de circulation sanguine du corps est réduit, cela peut entraîner des problèmes cardiaques et des complications.

## (optionnel) Références
https://ocean-climate.org/sensibilisation/la-circulation-oceanique/

**Comment by TDecabrat** [comment]
# Barrière de Corail | Système Immunitaire

## Évènement
Protection de l'environnement en question

## Zones à mettre en surbrillance
Carte du monde : Grande barrière de corail
Corps humain : Peau ou Os, au choix

## Nature et conséquences
Carte du monde : + de catastrophe (impact des mouvements maritimes moins retenus) + destruction écosystème (refuge pour de nombreux poissons) + grosse source d'O2 réduite, ...
Corps humain : Protection Immunitaire - Maladies

## (optionnel) Références
X
